#!/bin/sh
source /root/.bash_profile 
echo "*/1 * * * * sh $CODEROOTDIR/script/watchdog > /dev/null 2>&1" >> cron
echo "0 */3 * * * sh $CODEROOTDIR/script/clear_file_log > /dev/null 2>&1" >> cron
echo "10 1 * * * sh $CODEROOTDIR/script/jettyrestart > /dev/null 2>&1" >> cron
crontab -u root cron
rm -rf cron



