#!/bin/sh

info="告警进程(fysysmonitor) NFS管理主进程(fynfsmanager) SMB管理主进程(fysmbmanager) SFTP管理主进程(fysftpmanager) 流管理进程(fystreamanager) 文件同步进程(fyfilesync) FTP服务进程(fyftpserver) FTP管理主进程(fyftpmanager) 流控进程(fyflowcontrol) 调度进程(fychmanager)"
prog="fysftpmanager fysysmonitor fynfsmanager fysmbmanager  fystreamanager fyfilesync fyftpserver fyftpmanager fyflowcontrol fychmanager "

ipos=0
for i in $info
do
	echo  "关闭 $i ..."
	jpos=0
	for j in $prog
	do
		if [ $ipos -ne $jpos ]; then
#			jpos=`expr $jpos + 1`
			((jpos++))
			continue
		else
			$j stop > /dev/null 2>&1
			sleep 2
			number=`ps -u $LOGNAME | grep -c "[ ]$j\$"`
			if [ $number != 0 ] ; then
				echo "关闭程序 $j 失败"
			fi
			break
		fi
	done
	echo "关闭程序 $j 成功"
#	ipos=`expr $ipos + 1`
	((ipos++))
done

echo "..."

echo "进程检查"
ps -ef|grep $LOGNAME|grep fy


