#!/bin/sh

source /root/.bash_profile

cd $ODLLOGPATH

find ./ \( -name '*debug*' \) -ctime +3 -exec rm -f {} \;
find ./ \( -name '*error*' \) -ctime +3 -exec rm -f {} \;
find ./ \( -name '*info*' \) -ctime +3 -exec rm -f {} \;

cd $LOGPATH/watchdog

find ./ \( -name '*_watchdog*' \) -ctime +3 -exec rm -f {} \;

exit 0


