#!/bin/sh

source /root/.bash_profile

NOWTIME=$(date +%Y%m%d%H%M%S)
filename=`date +%Y%m%d`_watchdog.log
if [ ! -d $LOGPATH/watchdog ]
then
	mkdir -p $LOGPATH/watchdog
fi

echo "<==========${NOWTIME}==========>"	>>$LOGPATH/watchdog/$filename
#cd /root/
#source /root/.bash_profile
p_list="fychmanager fyflowcontrol fyftpmanager fyftpserver fyfilesync fystreamanager fysftpmanager fysmbmanager fynfsmanager fysysmonitor"
for p in ${p_list}; do
if [ -f .${p}id ]; then
        pid=`cat .${p}id`
else
        echo "$p is not run!Now begin to run ..." >>$LOGPATH/watchdog/$filename
        $p start >/dev/null
	continue
fi
i=`ps -ef|grep ${pid}|grep -v grep|awk '{ print $2 }'|grep $pid`
echo $i
if [ "${pid}" =  "${i}" ]; then
        echo "$p is running..." >>$LOGPATH/watchdog/$filename
else
        echo "$p is not run!Now begin to run ..." >>$LOGPATH/watchdog/$filename
        k_list=`ps -ef|grep $p|grep " 1 "|grep -v grep|awk '{print $2}'`
	if [ "${k_list}" != "" ];then
        	for j in $k_list; do
        		echo ${j} > /root/.${p}id
        	done
	else
        	$p start  >/dev/null
	fi
        sleep 2
fi

done

x=`ps -ef|grep "mysql"|grep -v grep|wc -l`
echo $x
if [ $x = 2 ]; then
        echo "mysql is running..." >>$LOGPATH/watchdog/$filename
else
        echo "mysql is not run!Now begin to run..." >>$LOGPATH/watchdog/$filename
		/usr/bin/systemctl start mariadb
fi

#y=`ps -ef|grep "/opt/jdk1.8.0_40/bin/java -jar /opt/jetty-distribution-9.2.10.v20150310/start.jar"|grep -v grep|wc -l`
y=`ps -ef|grep "org.apache.catalina.startup.Bootstrap start"|grep -v grep|wc -l`
echo $y
if [ $y = 1 ]; then
        echo "jetty is running..." >>$LOGPATH/watchdog/$filename
else
        echo "jetty is not run!Now begin to run..." >>$LOGPATH/watchdog/$filename
        /opt/jdwa/bin/adminserver
fi

z=`ps -ef|grep "/usr/local/clamav/sbin/clamd"|grep -v grep|wc -l`
echo $z
if [ $z = 1 ]; then
        echo "clamd is running..." >>$LOGPATH/watchdog/$filename
else
        echo "clamd is not run!Now begin to run..." >>$LOGPATH/watchdog/$filename
        /usr/local/clamav/sbin/clamd
fi

